export const RESTAURANT_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  USER: 'USER',
}

export const RESTAURANT_STATUS = {
  NONE: 'NONE',
  APPLICATION_PENDING: 'APPLICATION_PENDING',
  APPLICATION_PROCESSING: 'APPLICATION_PROCESSING',
  APPLICATION_ACCEPTED: 'APPLICATION_ACCEPTED',
  LIVE: 'LIVE',
  DISABLED: 'DISABLED',
}

export const RESTAURANT_REG_STEPS = {
  STEP_1_COMPLETE: 'STEP_1_COMPLETE',
  STEP_2_COMPLETE: 'STEP_2_COMPLETE',
  STEP_3_COMPLETE: 'STEP_3_COMPLETE',
  STEP_4_COMPLETE: 'STEP_4_COMPLETE',
}

export const RESTAURANT_SUBSCRIPTION_STATUS = {
  SUBSCRIBED: 'SUBSCRIBED',
  NOT_SUBSCRIBED: 'NOT_SUBSCRIBED',
}
