export const NOTIFICATION_EVENT_TYPES = {
  NEW_DEAL: 'NEW_DEAL',
  CHECKOUT_FEED: 'CHECKOUT_FEED',
}

export const NOTICATION_NATIVE_APP_TYPES = {
  SINGLE_DEAL: 'SINGLE_DEAL',
  HOME_FEED: 'HOME_FEED',
}
